# Generated by Django 4.2.7 on 2023-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=10, verbose_name="Document Type"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=10, verbose_name="Document Number"),
                ),
                ("code", models.CharField(max_length=8, verbose_name="Code")),
                (
                    "first_name",
                    models.CharField(max_length=256, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=256, verbose_name="Last Name"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
            ],
        ),
    ]
